/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './index';
import * as i2 from './componets/index';
export const MadhuCommonModuleNgFactory:i0.NgModuleFactory<i1.MadhuCommonModule> = i0.ɵcmf(i1.MadhuCommonModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,
          i2.MadhuCommonComponentModule,i2.MadhuCommonComponentModule,([] as any[])),
          i0.ɵmpd(512,i1.MadhuCommonModule,i1.MadhuCommonModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL21hZGh1cmFraGFsbWFnYXIvbGVhcm5pbmcvbGVhcm4tYW5ndWxhci9teWNvbXBvbmVudC9pbmRleC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9tYWRodXJha2hhbG1hZ2FyL2xlYXJuaW5nL2xlYXJuLWFuZ3VsYXIvbXljb21wb25lbnQvaW5kZXgudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
