/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './helloworld.component';
const styles_HelloWorldComponent:any[] = ([] as any[]);
export const RenderType_HelloWorldComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_HelloWorldComponent,data:{}});
export function View_HelloWorldComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted(-1,(null as any),[' My Component ']))],(null as any),(null as any));
}
export function View_HelloWorldComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'madhu-helloworld',
      ([] as any[]),(null as any),(null as any),(null as any),View_HelloWorldComponent_0,
      RenderType_HelloWorldComponent)),i0.ɵdid(1,49152,(null as any),0,i1.HelloWorldComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const HelloWorldComponentNgFactory:i0.ComponentFactory<i1.HelloWorldComponent> = i0.ɵccf('madhu-helloworld',
    i1.HelloWorldComponent,View_HelloWorldComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL21hZGh1cmFraGFsbWFnYXIvbGVhcm5pbmcvbGVhcm4tYW5ndWxhci9teWNvbXBvbmVudC9jb21wb25ldHMvaGVsbG93b3JsZC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvbWFkaHVyYWtoYWxtYWdhci9sZWFybmluZy9sZWFybi1hbmd1bGFyL215Y29tcG9uZW50L2NvbXBvbmV0cy9oZWxsb3dvcmxkLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL21hZGh1cmFraGFsbWFnYXIvbGVhcm5pbmcvbGVhcm4tYW5ndWxhci9teWNvbXBvbmVudC9jb21wb25ldHMvaGVsbG93b3JsZC5jb21wb25lbnQudHMuSGVsbG9Xb3JsZENvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvbWFkaHVyYWtoYWxtYWdhci9sZWFybmluZy9sZWFybi1hbmd1bGFyL215Y29tcG9uZW50L2NvbXBvbmV0cy9oZWxsb3dvcmxkLmNvbXBvbmVudC50cy5IZWxsb1dvcmxkQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPiBNeSBDb21wb25lbnQgPC9oMT4iLCI8bWFkaHUtaGVsbG93b3JsZD48L21hZGh1LWhlbGxvd29ybGQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBOzs7b0JDQUo7TUFBQTtvQ0FBQSxVQUFBO01BQUE7OzsifQ==
