/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './index';
export const MadhuCommonComponentModuleNgFactory:i0.NgModuleFactory<i1.MadhuCommonComponentModule> = i0.ɵcmf(i1.MadhuCommonComponentModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,
          i1.MadhuCommonComponentModule,i1.MadhuCommonComponentModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL21hZGh1cmFraGFsbWFnYXIvbGVhcm5pbmcvbGVhcm4tYW5ndWxhci9teWNvbXBvbmVudC9jb21wb25ldHMvaW5kZXgubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvbWFkaHVyYWtoYWxtYWdhci9sZWFybmluZy9sZWFybi1hbmd1bGFyL215Y29tcG9uZW50L2NvbXBvbmV0cy9pbmRleC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OyJ9
